services:
  n8n-app:
    container_name: n8n-app
    hostname: n8n
    image: 'n8nio/n8n:1.108.1'
    command: start
    restart: always
    environment:
      - SERVICE_FQDN_N8N_5678
      - 'N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}'
      - 'WEBHOOK_URL=${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - 'GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Sao_Paulo}'
      - 'TZ=${TZ:-America/Sao_Paulo}'
      - DB_TYPE=postgresdb
      - 'DB_POSTGRESDB_DATABASE=${POSTGRES_N8N_DB:-n8n}'
      - 'DB_POSTGRESDB_HOST=${POSTGRES_HOST:-n8n-postgresql}'
      - 'DB_POSTGRESDB_PORT=${POSTGRES_PORT:-5432}'
      - 'DB_POSTGRESDB_USER=${POSTGRES_USER:-postgres}'
      - 'DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-password}'
      - DB_POSTGRESDB_SCHEMA=public
      - EXECUTIONS_MODE=queue
      - 'QUEUE_BULL_REDIS_HOST=${REDIS_HOST:-n8n-redis}'
      - 'QUEUE_BULL_REDIS_PORT=${REDIS_PORT:-6379}'
      - QUEUE_BULL_REDIS_DB=0
      - 'QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}'
      - N8N_LOG_LEVEL=info
      - N8N_ENCRYPTION_KEY=$SERVICE_BASE64_N8N
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - 'NODE_FUNCTION_ALLOW_EXTERNAL=*'
      - N8N_PROXY_HOPS=1
    volumes:
      - 'n8n-data:/home/node/.n8n'
    depends_on:
      - n8n-postgresql
      - n8n-redis
    ports:
      - '${N8N_PORT:-8282}:${N8N_PORT:-8282}'
      - '5678:5678'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/ || exit 1'
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - default
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
  
  n8n-webhook:
    container_name: n8n-webhook
    hostname: n8n-webhook
    image: 'n8nio/n8n:1.108.1'
    command: webhook
    restart: always
    environment:
      - 'GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Sao_Paulo}'
      - 'TZ=${TZ:-America/Sao_Paulo}'
      - DB_TYPE=postgresdb
      - 'DB_POSTGRESDB_DATABASE=${POSTGRES_N8N_DB:-n8n}'
      - 'DB_POSTGRESDB_HOST=${POSTGRES_HOST:-n8n-postgresql}'
      - 'DB_POSTGRESDB_PORT=${POSTGRES_PORT:-5432}'
      - 'DB_POSTGRESDB_USER=${POSTGRES_USER:-postgres}'
      - 'DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-password}'
      - DB_POSTGRESDB_SCHEMA=public
      - EXECUTIONS_MODE=queue
      - 'QUEUE_BULL_REDIS_HOST=${REDIS_HOST:-n8n-redis}'
      - 'QUEUE_BULL_REDIS_PORT=${REDIS_PORT:-6379}'
      - QUEUE_BULL_REDIS_PASSWORD=$REDIS_PASSWORD
      - QUEUE_BULL_REDIS_DB=0
      - N8N_LOG_LEVEL=info
      - N8N_ENCRYPTION_KEY=$SERVICE_BASE64_N8N
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - 'NODE_FUNCTION_ALLOW_EXTERNAL=*'
      - N8N_PROXY_HOPS=1
    volumes:
      - 'n8n-data:/home/node/.n8n'
    depends_on:
      - n8n-redis
      - n8n-postgresql
    networks:
      - default
    ports:
      - '${WEBHOOK_PORT:-8383}:${WEBHOOK_PORT:-8383}'
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  n8n-worker:
    container_name: n8n-worker
    hostname: n8n-worker
    image: 'n8nio/n8n:1.108.1'
    command: worker
    restart: always
    environment:
      - 'GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Sao_Paulo}'
      - 'TZ=${TZ:-America/Sao_Paulo}'
      - DB_TYPE=postgresdb
      - 'DB_POSTGRESDB_DATABASE=${POSTGRES_N8N_DB:-n8n}'
      - 'DB_POSTGRESDB_HOST=${POSTGRES_HOST:-n8n-postgresql}'
      - 'DB_POSTGRESDB_PORT=${POSTGRES_PORT:-5432}'
      - 'DB_POSTGRESDB_USER=${POSTGRES_USER:-postgres}'
      - 'DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-password}'
      - DB_POSTGRESDB_SCHEMA=public
      - EXECUTIONS_MODE=queue
      - 'QUEUE_BULL_REDIS_HOST=${REDIS_HOST:-n8n-redis}'
      - 'QUEUE_BULL_REDIS_PORT=${REDIS_PORT:-6379}'
      - QUEUE_BULL_REDIS_DB=0
      - QUEUE_BULL_REDIS_PASSWORD=$REDIS_PASSWORD
      - N8N_LOG_LEVEL=info
      - N8N_ENCRYPTION_KEY=$SERVICE_BASE64_N8N
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - 'NODE_FUNCTION_ALLOW_EXTERNAL=*'
      - N8N_PROXY_HOPS=1
    volumes:
      - 'n8n-data:/home/node/.n8n'
    depends_on:
      - n8n-redis
      - n8n-postgresql
    networks:
      - default
    ports:
      - '${WORKER_PORT:-8484}:${WORKER_PORT:-8484}'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    env_file:
      - .env

  n8n-postgresql:
    container_name: n8n-postgresql
    hostname: n8n-postgresql
    image: ankane/pgvector
    restart: always
    ports:
      - '${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}'
    networks:
      - default
    volumes:
      - 'n8n-postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-n8n-postgresql}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_N8N_DB:-n8n}
    env_file:
      - .env
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

  n8n-redis:
    container_name: n8n-redis
    hostname: n8n-redis
    image: 'redis:alpine'
    restart: always
    command:
      - redis-server
      - '--requirepass'
      - $REDIS_PASSWORD
    volumes:
      - 'n8n-redis-data:/data'
    networks:
      - default
    ports:
      - '${REDIS_PORT:-6379}:${REDIS_PORT:-6379}'
    env_file:
      - .env
    healthcheck:
      test:
        - CMD
        - redis-cli
        - '-a'
        - $REDIS_PASSWORD
        - PING
      interval: 30s
      timeout: 10s
      retries: 5

  evolution-api:
    container_name: evolution-api
    hostname: evolution-api
    image: 'atendai/evolution-api:v2.2.3'
    volumes:
      - 'evolution-data:/lab_evolution/instances'
    networks:
      - default
    ports:
      - '${EVOLUTION_PORT:-8585}:8585'
    depends_on:
      - n8n-postgresql
      - n8n-redis
    environment:
      - SERVICE_FQDN_EVOLUTION_8080
      - 'SERVER_URL=${SERVICE_FQDN_EVOLUTION}'
      - AUTHENTICATION_API_KEY=$SERVICE_PASSWORD_EVOLUTION
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - 'DATABASE_CONNECTION_URI=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/${POSTGRES_EVOLUTION_DATABASE:-evolution}?schema=public'
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_exchange
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      - 'CONFIG_SESSION_PHONE_VERSION=${CONFIG_SESSION_PHONE_VERSION:-2.3000.1026231250}'
      - CACHE_REDIS_ENABLED=true
      - 'CACHE_REDIS_URI=redis://$REDIS_HOST:$REDIS_PORT/6'
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M

  coolify-base:
    container_name: coolify-base
    hostname: coolify-base
    build:
      context: ./coolify-base
      dockerfile: ./docker/development/Dockerfile
      args:
        - USER_ID=${USERID:-1000}
        - GROUP_ID=${GROUPID:-1000}
    ports:
      - "${BASE_PORT:-8181}:8080"
      - "9002:9000"
      - "80:8080"
    depends_on:
      - coolify-soketi
      - evolution-api
      - n8n-postgresql
      - n8n-redis
    networks:
      - default
    environment:
      AUTORUN_ENABLED: false
      PUSHER_HOST: "${PUSHER_HOST:-coolify-soketi}"
      PUSHER_PORT: "${PUSHER_PORT:-6001}"
      PUSHER_SCHEME: "${PUSHER_SCHEME:-http}"
      PUSHER_APP_ID: "${PUSHER_APP_ID:-coolify}"
      PUSHER_APP_KEY: "${PUSHER_APP_KEY:-coolify}"
      PUSHER_APP_SECRET: "${PUSHER_APP_SECRET:-coolify}"
      DATABASE_URL: "${DATABASE_URL:-postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/${POSTGRES_COOLIFY_DB:-coolify}?schema=public}"
      DB_HOST: "${POSTGRES_HOST:-n8n-postgresql}"
      DB_PORT: "${POSTGRES_PORT:-5432}"
      DB_DATABASE: "${POSTGRES_COOLIFY_DB:-n8n}"
      DB_USERNAME: "${POSTGRES_USER:-postgres}"
      DB_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRESQL_DATABASE: "${POSTGRES_COOLIFY_DB:-coolify}"
      SERVICE_USER_POSTGRESQL: "${POSTGRES_USER:-postgres}"
      SERVICE_PASSWORD_POSTGRESQL: "${POSTGRES_PASSWORD:-password}"
    volumes:
      - ./coolify-base:/var/www/html/:cached
      - coolify-backups-data:/var/www/html/storage/app/backups
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M

  coolify-soketi:
    container_name: coolify-soketi
    hostname: coolify-soketi
    build:
      context: ./coolify-base
      dockerfile: ./docker/coolify-realtime/Dockerfile
    ports:
      - "${FORWARD_SOKETI_PORT:-6001}:6001"
      - "6002:6002"
    volumes:
      - ./storage:/var/www/html/storage
      - ./coolify-base/docker/coolify-realtime/terminal-server.js:/terminal/terminal-server.js
    environment:
      SOKETI_DEBUG: "false"
      SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID:-coolify}"
      SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY:-coolify}"
      SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET:-coolify}"
    entrypoint: ["/bin/sh", "/soketi-entrypoint.sh"]
    networks:
      - default
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  coolify-app:
    container_name: coolify-app
    hostname: coolify-app
    image: node:24-alpine
    pull_policy: always
    working_dir: /var/www/html
    environment:
      VITE_HOST: "${VITE_HOST:-localhost}"
      VITE_PORT: "${VITE_PORT:-5173}"
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
      - "${APP_PORT:-8080}:5173"
    volumes:
      - ./coolify-base:/var/www/html/:cached
    command: sh -c "npm install && npm run dev"
    depends_on:
      - coolify-base
    networks:
      - default
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M

  coolify-testing-host:
    container_name: coolify-testing-host
    hostname: coolify-testing-host
    build:
      context: ./coolify-base
      dockerfile: ./docker/testing-host/Dockerfile
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - coolify-data:/data/coolify
      - coolify-backups-data:/data/coolify/backups
      - coolify-minio-data:/data/coolify/_volumes/minio
      - n8n-postgresql-data:/data/coolify/_volumes/database
      - n8n-redis-data:/data/coolify/_volumes/redis
    networks:
      - default
    ports:
      - '${TESTING_HOST_PORT:-8686}:8686'
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M

  coolify-mailpit:
    container_name: coolify-mailpit
    hostname: coolify-mailpit
    image: axllent/mailpit:latest
    pull_policy: always
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - default
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  coolify-minio:
    container_name: coolify-minio
    hostname: coolify-minio
    image: minio/minio:latest
    pull_policy: always
    command: server /data --console-address ":9001"
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_PORT_CONSOLE:-9001}:9001"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
    volumes:
      - coolify-minio-data:/data
    networks:
      - default
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M

volumes:
  n8n-data: null
  n8n-postgresql-data: null
  n8n-redis-data: null
  coolify-data:
  coolify-backups-data:
  coolify-minio-data:
  evolution-data: null

networks:
  default:
    driver: bridge